name: 'Create assessment'
description: ''
inputs: 
  creds:
    description: 'Azure credentials i.e. output of `az ad sp create-for-rbac --sdk-auth`'
    required: true
    default: ''
  resource-group:
    description: 'Resource Group Name'
    required: true
    default: ''
  cluster-name:
    description: 'AKS Cluster Name'
    required: true
    default: ''
  code:
    description: 'assessment code'
    required: true
    default: ''
  severity:
    description: 'Severity of the assessment'
    required: true
    default: 'Low'
  token:
    description: 'token'
    required: true
    default: '${{ github.token }}'
  commit-id:
    description: 'commit-id-for-container-scan'
    required: false
    default: '${{ github.event.client_payload.commit }}'
  assessment-title:
    description: 'assessment title'
    required: false
    default: ''
  upload-sarif:
    description: 'file path of a sarif you want to upload'
    required: false
    default: ''
  web-app-name:
    description: 'Web app name'
    required: false
    default: ''
branding:
  color: 'green' # optional, decorates the entry in the GitHub Marketplace
runs:
  using: 'node12'
  main: 'lib/login.js'
